// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using axiomtechno.Data;

#nullable disable

namespace axiomtechno.Migrations
{
    [DbContext(typeof(axiomtechnoContext))]
    [Migration("20260422000045_axiom")]
    partial class axiom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("axiomtechno.Models.Clientes", b =>
                {
                    b.Property<int>("ClId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClId"));

                    b.Property<bool>("ClActivo")
                        .HasColumnType("bit");

                    b.Property<string>("ClDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ClFechaAlta")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ClFechaBaja")
                        .HasColumnType("date");

                    b.Property<string>("ClImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClTelefono")
                        .HasColumnType("bigint");

                    b.Property<string>("ClUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("axiomtechno.Models.Pagos", b =>
                {
                    b.Property<int>("PagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagId"));

                    b.Property<int>("ClId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteClId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PagFecha")
                        .HasColumnType("date");

                    b.Property<decimal>("PagMonto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagId");

                    b.HasIndex("ClienteClId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("axiomtechno.Models.Roles", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("axiomtechno.Models.Usuarios", b =>
                {
                    b.Property<int>("UsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsId"));

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<bool>("UsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("UsApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsCorreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UsDni")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UsFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UsFechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsTelefono")
                        .HasColumnType("bigint");

                    b.Property<string>("token_recovery")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsId");

                    b.HasIndex("RolID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("axiomtechno.Models.Pagos", b =>
                {
                    b.HasOne("axiomtechno.Models.Clientes", "Cliente")
                        .WithMany("Pagos")
                        .HasForeignKey("ClienteClId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("axiomtechno.Models.Usuarios", b =>
                {
                    b.HasOne("axiomtechno.Models.Roles", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("axiomtechno.Models.Clientes", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("axiomtechno.Models.Roles", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
